version: "3"
services:
  autogen-studio:
    image: ghcr.io/lludlow/autogen-studio
    environment:
      - OPENAI_API_KEY=YOUR_API_KEY
    volumes:
      - ./data:/app/.autogenstudio
    ports:
      - 8081:8081